# Generated by Django 3.2.4 on 2021-06-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'Plain'), ('H', 'Hawaiian'), ('X', 'Extra Cheese'), ('PP', 'Pepperoni'), ('M', 'Mushroom'), ('V', 'Veggie')], max_length=20)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enzo_pizzeria.pizza')),
            ],
        ),
    ]
